site_name: Thunder
plugins:
- search
- mkdocstrings:
    watch:
        - src/thunder


repo_name: Thunder speech
repo_url: https://github.com/scart97/thunder-speech
edit_uri: ""

theme:
  name: material
