name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.1.6
      - name: View poetry version
        run: poetry --version
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1
          poetry install
      - name: Build docs
        run: mkdocs build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/
