
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test pull request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python Poetry
      uses: abatilo/actions-poetry@v2.1.4
      with:
        poetry-version: 1.1.6
    - name: View poetry version
      run: poetry --version
    - name: Install library
      run: |
        sudo apt-get update
        sudo apt-get install libsndfile1
        poetry install
    - name: Test with pytest
      run: |
        HYPOTHESIS_PROFILE="ci" RUN_SLOW=1 poetry run pytest -sv --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        env_vars: PYTHON
        name: codecov-thunder
        fail_ci_if_error: true
